const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {startWorker}=require('./worker-server.cjs');
const G=require('../game.js');
const data=require('../anime_list.json');
(async()=>{
 const worker=await startWorker();
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1360,height:1080}});
  await context.route(/https:\/\//,route=>route.abort());
  const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const base=worker.base;
  const tag=(kind,name)=>page.locator('#'+kind+'Tags').getByRole('checkbox',{name,exact:true});
  const add=async(kind,name)=>{await page.fill('#'+kind+'TagInput',name);await page.click(kind==='exclude'?'#addExcludeTag':'#addIncludeTag');};
  await page.goto(base);await page.fill('#playerName','筛选测试');await page.click('#createRoom');
  await page.waitForFunction(()=>allAnime.length>200);
  await page.click('#roomFilters');
  await expect(page.locator('#filterForm input[type=range]')).toHaveCount(5);
  // Presets are the cold-start path: one chip, a whole pool, no dialog left open.
  await expect(page.locator('.preset-chip')).toHaveCount(5);
  await expect(page.locator('.preset-chip[aria-pressed=true]')).toHaveCount(0);
  await page.getByRole('button',{name:'近五年',exact:true}).click();
  await expect(page.locator('#filterDialog')).toBeVisible();
  await expect(page.locator('#minYear')).toHaveValue(String(G.dataYear-4));
  await expect(page.locator('#minYearRange')).toHaveValue(String(G.dataYear-4));
  await expect(page.locator('#maxYear')).toHaveValue(String(G.dataYear));
  await expect(page.getByRole('button',{name:'近五年',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.preset-chip[aria-pressed=true]')).toHaveCount(1);
  const presetPool=await page.evaluate(()=>G.filter(allAnime,readFilters(),G.dataDate).length);
  assert.ok(presetPool>=25,'a preset must never leave the pool unplayable');
  await expect(page.locator('#poolCount')).toHaveText('候选池：'+presetPool.toLocaleString()+' 部');
  await expect(page.locator('#applyFilters')).toBeEnabled();
  // Nudging any dial by hand drops the chip's pressed state.
  await page.locator('#minYearRange').focus();await page.keyboard.press('ArrowRight');
  await expect(page.locator('.preset-chip[aria-pressed=true]')).toHaveCount(0);
  await page.getByRole('button',{name:'人气佳作',exact:true}).click();
  await expect(page.locator('#minVotes')).toHaveValue('2500');await expect(page.locator('#minScore')).toHaveValue('7');
  await expect(page.locator('#minYear')).toHaveValue('');
  // A preset moves the dials only: the host's tag choices survive it.
  await add('include','预设保留');
  await page.getByRole('button',{name:'热门',exact:true}).click();
  await expect(tag('include','预设保留')).toBeChecked();
  await page.getByRole('button',{name:'删除包含标签 预设保留',exact:true}).click();
  await page.fill('#minVotes','500');await page.fill('#minYear','');await page.fill('#maxYear',String(G.dataYear));
  await page.fill('#minVotes','600');await expect(page.locator('#minVotesRange')).toHaveValue('600');
  await page.locator('#minVotesRange').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#minVotes')).toHaveValue('601');
  await page.fill('#minVotes','500');
  await page.fill('#minYear','2000');await expect(page.locator('#minYearRange')).toHaveValue('2000');
  await page.locator('#minYearRange').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#minYear')).toHaveValue('2001');
  await page.fill('#minYear','');
  await page.fill('#maxYear','2024');await expect(page.locator('#maxYearRange')).toHaveValue('2024');await page.fill('#maxYear','2026');
  await page.locator('#minScoreRange').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');
  await expect(page.locator('#minScore')).toHaveValue('0.1');
  await page.fill('#minScore','6');await expect(page.locator('#minScoreRange')).toHaveValue('6');
  await page.fill('#maxScore','9');await expect(page.locator('#maxScoreRange')).toHaveValue('9');
  await page.fill('#maxScore','5');await expect(page.locator('#applyFilters')).toBeDisabled();
  await page.fill('#maxScore','9.05');await expect(page.locator('#applyFilters')).toBeDisabled();
  await page.fill('#maxScore','9');
  await tag('exclude','剧场版').uncheck();
  await add('include','音乐');await add('include','TV');
  await expect(tag('exclude','剧场版')).not.toBeChecked();await expect(tag('include','音乐')).toBeChecked();
  await add('exclude','原创');
  await add('include','未勾选的标签');await tag('include','未勾选的标签').uncheck();
  await add('exclude','未勾选排除');await tag('exclude','未勾选排除').uncheck();
  await add('include','音乐');await expect(tag('include','音乐')).toHaveCount(1);
  await expect(tag('include','未勾选的标签')).not.toBeChecked();
  await add('include','删除测试');await page.getByRole('button',{name:'删除包含标签 删除测试',exact:true}).click();
  await expect(tag('include','删除测试')).toHaveCount(0);
  await expect(tag('include','TV')).toBeChecked();await expect(tag('exclude','原创')).toBeChecked();
  await page.fill('#includeTagInput','OVA');await page.locator('#includeTagInput').press('Enter');
  await expect(page.locator('#filterDialog')).toBeVisible();await expect(page.locator('#applyFilters')).toBeDisabled();
  await page.getByRole('button',{name:'删除包含标签 OVA',exact:true}).click();
  await expect(tag('exclude','OVA')).toBeChecked();
  const selected=await page.evaluate(()=>readFilters());
  const expected=G.filter(data,selected).length;assert.ok(expected>=25);
  await expect(page.locator('#poolCount')).toHaveText('候选池：'+expected.toLocaleString()+' 部');
  fs.mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/filters-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>document.getElementById('filterDialog').scrollTop=0);
  await page.screenshot({path:'artifacts/filters-mobile.png'});
  assert.ok(await page.evaluate(()=>{
   const dialog=document.getElementById('filterDialog'),left=document.getElementById('excludeTags').getBoundingClientRect(),right=document.getElementById('includeTags').getBoundingClientRect();
   return dialog.scrollWidth<=dialog.clientWidth && document.documentElement.scrollWidth<=innerWidth && left.x<right.x;
  }));
  await page.evaluate(()=>document.getElementById('filterDialog').scrollTop=document.getElementById('filterDialog').scrollHeight);
  await page.screenshot({path:'artifacts/filters-mobile-tags.png'});
  const saveBounds=await page.locator('#applyFilters').boundingBox();assert.ok(saveBounds.y+saveBounds.height<=844);
  await page.click('#applyFilters');await expect(page.locator('#filterDialog')).not.toBeVisible();
  await expect(page.locator('#roomPoolCount')).toHaveText(expected.toLocaleString());
  await page.reload();await page.click('#roomFilters');await page.waitForFunction(()=>allAnime.length>200);
  await expect(tag('include','未勾选的标签')).not.toBeChecked();await expect(tag('exclude','未勾选排除')).not.toBeChecked();
  await expect(tag('exclude','剧场版')).not.toBeChecked();await expect(tag('include','音乐')).toBeChecked();
  await expect(page.locator('#minScore')).toHaveValue('6');await expect(page.locator('#maxScore')).toHaveValue('9');
  await tag('include','音乐').uncheck();await add('exclude','取消测试');await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.click('#roomFilters');await expect(tag('include','音乐')).toBeChecked();await expect(tag('exclude','取消测试')).toHaveCount(0);
  await page.getByRole('button',{name:'删除排除标签 未勾选排除',exact:true}).click();
  await page.click('#applyFilters');await expect(page.locator('#filterDialog')).not.toBeVisible();
  await page.click('#roomFilters');await expect(tag('exclude','未勾选排除')).toHaveCount(0);
  // Shared controls must also apply successfully in local practice.
  await page.goto(base+'/?local');await page.waitForSelector('.card');await page.click('#filterButton');
  await page.fill('#minScore','6');await add('include','TV');await page.click('#applyFilters');
  await expect(page.locator('#filterDialog')).not.toBeVisible();await expect(page.locator('.card')).toHaveCount(25);
  await page.click('#filterButton');await expect(tag('include','TV')).toBeChecked();
  assert.deepEqual(errors,[]);
  console.log('Filter sliders, tag drafts, combined matching, room persistence, cancellation, mobile layout and local apply passed.');
 }finally{await browser.close();await worker.stop();}
})().catch(e=>{console.error(e);process.exit(1);});
