'use strict';
// Downloads the anime data that logicolors/bangumi-master crawls every week and
// writes fallback-data.js from it. All three files are ignored by git, so the
// dataset never piles up in history. With --if-missing (what the build uses) a
// copy already on disk is reused; without it the script always downloads, and
// falls back to the copy on disk only if the download fails.
const fs = require('node:fs');
const path = require('node:path');
const G = require('../game.js');
const root = path.join(__dirname, '..');
const source = 'https://raw.githubusercontent.com/logicolors/bangumi-master/master/data/';
const listFile = path.join(root, 'anime_list.json');
const metaFile = path.join(root, 'anime_meta.json');
const fallbackFile = path.join(root, 'fallback-data.js');

// raw.githubusercontent.com drops connections now and then, so retry a few times.
async function download(name, tries = 3) {
  for (let attempt = 1; ; attempt++) {
    try {
      const response = await fetch(source + name, {signal: AbortSignal.timeout(120000)});
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return await response.text();
    } catch (error) {
      const reason = error.cause?.code || error.cause?.message || error.message;
      if (attempt >= tries) throw new Error(`${name}: ${reason}`);
      console.warn(`${name}: ${reason}; retrying (${attempt}/${tries - 1})`);
    }
  }
}

function parse(listText, metaText) {
  const list = JSON.parse(listText), meta = JSON.parse(metaText);
  if (!Array.isArray(list) || list.length < 25) throw new Error('anime_list.json is not a usable list');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(meta?.collected_at)) throw new Error('anime_meta.json has no collected_at date');
  return {list, date: meta.collected_at};
}

const onDisk = () => fs.existsSync(listFile) && fs.existsSync(metaFile);
const readDisk = () => parse(fs.readFileSync(listFile, 'utf8'), fs.readFileSync(metaFile, 'utf8'));

async function main() {
  let data;
  if (process.argv.includes('--if-missing') && onDisk()) data = readDisk();
  else {
    try {
      const [listText, metaText] = await Promise.all([download('anime_list.json'), download('anime_meta.json')]);
      data = parse(listText, metaText);
      // The list is saved byte for byte as bangumi-master publishes it.
      fs.writeFileSync(listFile, listText);
      fs.writeFileSync(metaFile, metaText);
      console.log(`Downloaded ${data.list.length} titles collected on ${data.date}.`);
    } catch (error) {
      if (!onDisk()) throw error;
      console.warn(`Download failed (${error.message}); using the copy on disk.`);
      data = readDisk();
    }
  }
  // G.defaults carries the stand-in year in Node, so the year cap follows the data.
  const filters = {...G.defaults, maxYear: Number(data.date.slice(0, 4))};
  const records = G.filter(data.list, filters, data.date).sort((a, b) => b.vote_count - a.vote_count).slice(0, 200);
  fs.writeFileSync(fallbackFile, '// Generated by scripts/update-data.cjs. The date the data was collected, and a\n// local snapshot of 200 popular eligible Bangumi titles, including cover URLs.\n'
    + `window.ANICODE_DATA_DATE = ${JSON.stringify(data.date)};\nwindow.ANICODE_FALLBACK = ${JSON.stringify(records)};\n`);
  console.log(`Data date ${data.date}; fallback pool ${records.length} titles.`);
}

main().catch(error => { console.error(`Could not update anime data: ${error.message}`); process.exit(1); });
